# Site settings
title: Fluid Frenzy
email: fluidfrenzy@gmail.com
description: >
  GPU Fluid Simulation.
lang: en-US

baseurl: "/fluidfrenzy" # the subpath of your site, e.g. /blog/
url: https://frenzybyte.github.io/fluidfrenzy # the base hostname & protocol for your site
git_address: https://github.com/frenzybyte/fluidfrenzy
git_edit_address: https://github.com/FrenzyByte/fluidfrenzy/blob/main
git_issue_address: https://github.com/FrenzyByte/fluidfrenzy/issues
twitter_address: https://twitter.com/FluidFrenzy
unityasset_address: https://assetstore.unity.com/packages/slug/273366
youtube_address: https://www.youtube.com/@Fluid-Frenzy
reddit_address: https://www.reddit.com/u/FrenzyTheHedgehog/


# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: slate # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

kramdown:
    toc_levels: "1,2,3,4"